#!/bin/sh

if [ -z "$1" -o -z "$2" ]; then
  echo "build <package> <version>"
  exit 1
elif [ ! -d "$1" ]; then
  echo "invalid package \"$1\""
  exit 1
fi

mkdir -p packages
docker build -t fpm -v "$PWD/$1:/scripts" --build-arg version=$2 .
docker run -v "$PWD/packages:/packages" -v "$PWD/$1:/scripts" --rm --entrypoint "/scripts/entrypoint.sh" fpm $2
