#!/bin/sh

# set -e

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
  echo "build <package> <version> <distro>"
  exit 1
elif [ ! -d "$1" ]; then
  echo "invalid package \"$1\""
  exit 1
fi

function distro_name {
  local IFS=':'; read -ra parts <<< "$1" # split on ":"
  printf "%s" "${parts[@]}"              # concatenate
}

function version_split {
  local IFS=':'; read -ra parts <<< "$1" # split on ":"
  printf "%s" "${parts[$2]:=1}"
}

package=$1
version=$( version_split "$2" 0 )
iteration=$( version_split "$2" 1 )
distro=$( distro_name "$3" )

mkdir -p packages

docker build -t "fpm-${distro}" -f "Dockerfile.${distro}" .

docker run \
  --volume "$PWD/packages:/packages" \
  --volume "$PWD/${package}:/scripts" \
  --env-file "$PWD/.env" \
  --env "PACKAGE_VERSION=${version}" \
  --env "PACKAGE_ITERATION=${iteration}" \
  --env "PACKAGE_DISTRO=${distro}" \
  --entrypoint "/scripts/entrypoint" \
  "fpm-${distro}"
