FROM centos:7

ENV LANG en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8

RUN \
  rm -rf /var/cache/yum/timedhosts.txt /var/cache/yum/* && \
  yum -y -q -e 0 clean all && \
  yum -y -q -e 0 install epel-release && \
  yum -y -q -e 0 group install "Development Tools" && \
  yum -y -q -e 0 install which rpm-build git-core bzip2 ruby ruby-devel rubygems && \
  gem install fpm --no-rdoc --no-ri
