FROM fedora:28

ENV LANG en_US.UTF-8
ENV LC_CTYPE en_US.UTF-8

RUN \
  rm -rf /var/cache/yum/timedhosts.txt /var/cache/yum/* && \
  yum -y -q -e 0 clean all && \
  yum -y -q -e 0 group install "Development Tools" && \
  yum -y -q -e 0 install redhat-rpm-config rpm-build cmake bzip2 which ruby ruby-devel rubygems python2 && \
  gem install fpm --no-rdoc --no-ri
