#!/bin/bash

set -e

PREFIX=/opt/elixir

source "/scripts/${PACKAGE_DISTRO}.sh"

install_erlang

git clone --branch v$PACKAGE_VERSION --depth 1 https://github.com/elixir-lang/elixir.git $PREFIX
( cd $PREFIX && make )

cat << EOF > /tmp/after-install
ln -s $PREFIX/bin/{iex,mix,elixir,elixirc} /usr/local/bin
EOF

cat << EOF > /tmp/before-remove
rm -f /usr/local/bin/{iex,mix,elixir,elixirc}
EOF

fpm --input-type dir --output-type rpm --package /packages --rpm-dist $PACKAGE_DISTRO \
  --name elixir --version $PACKAGE_VERSION --iteration $PACKAGE_ITERATION \
  --depends "${DISTRO_ERLANG}" \
  --rpm-summary 'The Elixir programming language' \
  --description 'Elixir is a dynamic, functional language designed for building scalable and maintainable applications.' \
  --url 'https://elixir-lang.org/' \
  --license 'Apache 2.0' \
  --maintainer "${PACKAGE_MAINTAINER}" \
  --vendor "${PACKAGE_VENDOR}" \
  --after-install /tmp/after-install \
  --before-remove /tmp/before-remove \
  --force \
  $PREFIX
