#!/bin/bash

set -e

PREFIX=/opt/julia
CMAKE_MAJOR=${CMAKE_MAJOR:=3}
CMAKE_MINOR=${CMAKE_MINOR:=12}
CMAKE_POINT=${CMAKE_POINT:=1}
CMAKE="${CMAKE_MAJOR}.${CMAKE_MINOR}.${CMAKE_POINT}"

source "/scripts/${PACKAGE_DISTRO}.sh"

yum -y -q -e 0 install clang m4 $DISTRO_GFORTRAN

install_cmake

git clone --branch v$PACKAGE_VERSION --depth 1 https://github.com/JuliaLang/julia.git $PREFIX
( cd $PREFIX && make USEGCC=0 USECLANG=1 )

cat << EOF > /tmp/after-install
ln -s $PREFIX/bin/julia /usr/local/bin
EOF

cat << EOF > /tmp/before-remove
rm -f /usr/local/bin/julia
EOF

fpm --input-type dir --output-type rpm --package /packages --rpm-dist $PACKAGE_DISTRO \
  --name julia --PACKAGE_VERSION $PACKAGE_VERSION --PACKAGE_ITERATION $PACKAGE_ITERATION \
  --rpm-summary 'The Julia programming language' \
  --description 'Julia is a high-level, high-performance dynamic language for technical computing.' \
  --url 'https://julialang.org/' \
  --license 'Apache 2.0' \
  --maintainer "${PACKAGE_MAINTAINER}" \
  --vendor "${PACKAGE_VENDOR}" \
  --after-install /tmp/after-install \
  --before-remove /tmp/before-remove \
  --force \
  $PREFIX
