#!/bin/bash

set -e

PREFIX=/opt/julia

source "/scripts/functions.sh"
source "/scripts/${PACKAGE_DISTRO}.sh"

$DISTRO_PKG install clang m4 pcre2 pcre2-devel $DISTRO_BUILDDEPS

install_custom_deps

git clone --branch v$PACKAGE_VERSION --depth 1 https://github.com/JuliaLang/julia.git $PREFIX
( cd $PREFIX && make -j4 USEGCC=0 USECLANG=1 )

cat << EOF > /tmp/after-install
ln -s $PREFIX/bin/julia /usr/local/bin
EOF

cat << EOF > /tmp/before-remove
rm -f /usr/local/bin/julia
EOF

fpm --input-type dir --output-type rpm \
  --package /packages --rpm-dist $PACKAGE_DISTRO \
  --depends pcre2 $DISTRO_PKGDEPS \
  --name julia --version $PACKAGE_VERSION --iteration $PACKAGE_ITERATION \
  --rpm-summary 'The Julia programming language' \
  --description 'Julia is a high-level, high-performance dynamic language for technical computing.' \
  --url 'https://julialang.org/' \
  --license 'Apache 2.0' \
  --maintainer "${PACKAGE_MAINTAINER}" \
  --vendor "${PACKAGE_VENDOR}" \
  --after-install /tmp/after-install \
  --before-remove /tmp/before-remove \
  --force \
  $PREFIX
